[build]
  command = "npm install && npx prisma generate && npm run build"
  publish = ".next"

[build.processing]
  skip_processing = false

[build.processing.css]
  bundle = true
  minify = true

[build.processing.js]
  bundle = true
  minify = true

[build.environment]
  NODE_VERSION = "22"
  NPM_FLAGS = "--production=false"

[[plugins]]
  package = "@netlify/plugin-nextjs"
